---
title: "Body size patterns"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

Plots for the manuscript

```{r Load data, message=FALSE}
library(itsadug)
library(gratia)
library(arm)
library(relaimpo)
library(GGally)
# library(linkedModels)
library(arrayhelpers)
library(mgcv)
library(tidyverse)
library(gridExtra)


#RECALCULATE gr for dataset. Filtering by maxSampleInterval in the creat ddddG step leaves in trailing lengths from the long samp intervals
# d2 <- d2 %>%
#   group_by(tag) %>%
#   # arrange(tag,sampleNumber) %>%
#   mutate( lagObservedWeight = lead(observedWeight),
#           lagObservedLength = lead(observedLength),
#           grWeight = exp(lagObservedWeight - observedWeight)/as.numeric((lagDetectionDate - detectionDate)),
#           grLength = (lagObservedLength - observedLength)/as.numeric((lagDetectionDate - detectionDate))
#   )  %>%
#   ungroup()


load("D:/projects/linkedModels/data/cd_west_1997.RData")
cd <- cd %>% mutate(observedWeight = ifelse(observedWeight == -9999.9, NA, observedWeight),
                    lagObservedWeight = ifelse(lagObservedWeight == -9999.9, NA, lagObservedWeight))
```

```{r theme_publication}

theme_publication <- function(base_size=14, base_family="") {
  library(grid)
  library(ggthemes)
  (theme_foundation(base_size=base_size, base_family=base_family)
    + theme(plot.title = element_text(face = "bold",
                                      size = rel(1.2), hjust = 0.5),
            text = element_text(),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            axis.title = element_text(face = "bold",size = rel(1)),
            axis.title.y = element_text(angle=90,vjust =2),
            axis.title.x = element_text(vjust = -0.2),
            axis.text = element_text(),
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            panel.grid.major = element_line(colour="#f0f0f0"),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.position = "bottom",
            legend.direction = "horizontal",
            legend.key.size= unit(0.2, "cm"),
            #    legend.margin = unit(0, "cm"),
            legend.title = element_text(face="italic"),
            plot.margin=unit(c(10,5,5,5),"mm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(face="bold"),
            panel.border = element_rect(colour = "black")
    ))

}
```


```{r gams for body size - data prep}
speciesIn <- 'bkt'
depVarIn <- 'observedLength'
kIn <- 4 # # of knots for the species and river smooths


vB <- 
  cd %>% mutate( age = year - cohort,
                 metaPop01 = ifelse(riverOrdered == 'wb obear', 0 ,1),
                 ydayCumul = yday + 365 * (year - cohort),
                 cf = observedWeight/observedLength^3 * 10000 ) %>%
    filter( ageInSamples %in% 1:9,
            age < 3, 
            year < 2016, area %in% c('inside','trib'), enc == 1
            #!(riverOrdered == 'wb mitchell' & ageInSamples > 8) #low sample sizes
            ) %>%
    filter(!(cohort < 2002 & river %in% c('wb jimmy','wb mitchell','wb obear'))) # added 7/25/2019. Limits tribs to after 2002

cohortOffset <- 2006

# 1-way
vB$cohortFactor <- factor(vB$cohort)
vB$cohortOrdered <- factor(vB$cohort, levels = 2000:2013, ordered = T)
#vB$cohortFactorCentered <- vB$cohortFactor - 2006
vB$cohortCentered <- vB$cohort - cohortOffset

vB$speciesFactor <- factor(vB$species, levels = c('bkt','bnt'))
vB$speciesOrdered <- factor(vB$species, levels = c('bkt','bnt'), ordered = T)

vB$riverFactor <- factor(vB$river, levels=c('west brook', 'wb jimmy', 'wb mitchell', 'wb obear'))
#vB$riverOrdered <- riverOrdered exists

# 2-way
vB$speciesRiverFactor <- factor(paste(vB$speciesFactor,vB$riverFactor, sep = '_'))
vB$cohortRiverFactor <- factor(paste(vB$cohortFactor,vB$riverFactor, sep = '_'))
vB$seasonRiverFactor <- factor(paste(vB$season,vB$riverFactor, sep = '_'))

vB$speciesRiverOrdered <- factor(paste(vB$speciesOrdered,vB$riverOrdered, sep = '_'), ordered = T)
vB$speciesCohortOrdered <- factor(paste(vB$speciesOrdered,vB$cohortOrdered, sep = '_'), ordered = T)
vB$cohortRiverOrdered <- factor(paste(vB$cohortOrdered,vB$riverOrdered, sep = '_'), ordered = T)

# 3-way
vB$cohortSpeciesRiverOrdered <- factor(paste(vB$cohortOrdered,vB$speciesOrdered,vB$riverOrdered, sep = '_'), ordered = T)

vB$tagIndexFactor <- factor(vB$tagIndex)

#vB$riverOrdered <- factor(vB$river,
#                         levels=c('west brook', 'wb jimmy', 'wb mitchell', 'wb obear'),
#                         ordered = T)

vB$salmon01 <- ifelse(vB$cohort <= 2004 & vB$river == 'west brook', 1, 0)

vB$speciesGG <- factor(vB$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)
vB$seasonGG <- factor(vB$season, levels = 1:4, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
vB$riverGG <- factor(vB$riverFactor,
                         levels=c('west brook', 'wb jimmy', 'wb mitchell',"wb obear"),
                         labels = c("West Brook","Open Large","Open Small","Isolated Small"))

# scaling temperature and flow
vB$meanTemperatureScaled <- as.numeric(scale(vB$meanTemperature))
vB$meanFlowScaled <- as.numeric(scale(vB$meanFlow))
vB$meanTemperatureFlowScaled <- vB$meanTemperatureScaled * vB$meanFlowScaled

seasonalTF <- vB %>% group_by(season) %>%
  summarize(meanTBySeason = mean(meanTemperature, na.rm = TRUE),
            sdTBySeason = sd(meanTemperature, na.rm = TRUE),
            meanFBySeason = mean(meanFlow, na.rm = TRUE),
            sdFBySeason = sd(meanFlow, na.rm = TRUE))

vB <- left_join(vB,seasonalTF) %>%
  mutate(meanTemperatureScaledBySeason = (meanTemperature - meanTBySeason)/sdTBySeason, 
         meanFlowScaledBySeason = (meanFlow - meanFBySeason)/sdFBySeason)

vB$meanTemperatureFlowScaledBySeason <- vB$meanTemperatureScaledBySeason * vB$meanFlowScaledBySeason

########################################
# tags that may need cohort fixes

#           tag
# 1  00088cc1c3
# 2  00088cc5c8
# 3  00088d0a10
# 4  00088d1a28
# 5  00088d20f5
# 6  00088d215f
# 7  00088d23b4
# 8  0009f6ecc2
# 9  0009f6edf1
# 10 0009f6ee11
# 11 0009f6f33c
# 12 0009f6f404
# 13 1bf20e52f0
# 14 1bf20ebfa7
########################################
```

```{r cohort strength}

cohortStrength <- vB %>%
  distinct(tagIndex, species, metaPop01, cohort) %>% #ignoring 10 fish that were in both o'bear and WB
  group_by(species, metaPop01, cohort) %>%
  summarize(cohortStrength = n()) %>%
  filter(!(cohort < 2000 & species !='ats')) %>% # no trib data
  mutate(cohortStrengthScaled = scale(cohortStrength))

#ggplot(cohortStrength, aes(cohortStrengthScaled, color = species)) + geom_freqpoly()

vB <- left_join(vB, cohortStrength)
# 
# cohortStrengthWide <- spread(cohortStrength, species, cohortStrengthScaled) %>%
#   rename(cohortStrengthScaledBKT = bkt,
#          cohortStrengthScaledBNT = bnt,
#          cohortStrengthScaledATS = ats
#          ) %>%
#   dplyr::select(-cohortStrength) %>%
#   ungroup()

cohortStrengthWide <- cohortStrength %>%
  dplyr::select(-cohortStrength) %>%
  spread( species, cohortStrengthScaled) %>%
  rename(cohortStrengthScaledBKT = bkt,
         cohortStrengthScaledBNT = bnt,
         cohortStrengthScaledATS = ats
         ) %>%
  ungroup()

vB <- left_join(vB, cohortStrengthWide)

vB$cohortStrengthScaledBKT2p5 <- ifelse(is.na(vB$cohortStrengthScaledBKT), -2.5, vB$cohortStrengthScaledBKT)
vB$cohortStrengthScaledBNT2p5 <- ifelse(is.na(vB$cohortStrengthScaledBNT), -2.5, vB$cohortStrengthScaledBNT)
vB$cohortStrengthScaledATS2p5 <- ifelse(is.na(vB$cohortStrengthScaledATS), -2.5, vB$cohortStrengthScaledATS)

vB$cohortStrength01BKT <- ifelse(is.na(vB$cohortStrengthScaledBKT), 0, 1)
vB$cohortStrength01BNT <- ifelse(is.na(vB$cohortStrengthScaledBNT), 0, 1)
vB$cohortStrength01ATS <- ifelse(is.na(vB$cohortStrengthScaledATS), 0, 1)


cohortStrength$speciesGG <- factor(cohortStrength$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"))

ggplot(cohortStrength %>% filter(cohort >= 2002), aes(cohort, cohortStrengthScaled, group = speciesGG, shape = speciesGG, color = speciesGG)) +
  geom_point(size = 3) +
  geom_line(size = 1.2) +
  labs(x = 'Cohort',
       y = 'Cohort strength',
       shape = 'Species', color='Species') +
  theme_publication(base_size = 20) +
  scale_color_grey() +
  theme(legend.position = "none",
        #legend.position=c(0.8, 0.8),
    #legend.direction = "vertical",
    #legend.title = element_text(face = "plain"),
    strip.background = element_blank(),
    strip.text.y = element_blank()) +
  facet_grid(metaPop01 ~ .)


ggsave('./figures/cohortStrengthByMetapop.png', width = 11, height = 8, units='in')


ggplot(cohortStrengthWide %>% filter(cohort >= 2002, metaPop01 == 1), aes(cohortStrengthScaledBKT, cohortStrengthScaledBNT)) +
  geom_point(size = 4) +
  geom_smooth(method = 'lm', se = FALSE, color = 'grey30') +
  theme_publication(base_size = 24) +
  labs(x = 'Brook Trout cohort strength',
       y = 'Brown Trout cohort strength') +
  xlim(c(-1.4,1.9)) +
  theme(legend.position = "none")

ggsave('./figures/cohortStrengthBKT_BNT.png', width = 11, height = 8, units='in')

CS_bkt_bnt <- lm(cohortStrengthScaledBNT ~ cohortStrengthScaledBKT, data = cohortStrengthWide %>% filter(cohort >= 2002, metaPop01 == 1))

summary(CS_bkt_bnt)

# bkt, metapop comparison
cohortStrengthWideBKT <- cohortStrengthWide %>%
  select(-cohortStrengthScaledATS,-cohortStrengthScaledBNT) %>%
  spread( metaPop01, cohortStrengthScaledBKT) %>%
  rename(metaPop0 = `0`, metaPop1 = `1`)

ggplot(cohortStrengthWideBKT %>% filter(cohort >= 2002), aes(metaPop1, metaPop0)) +
  geom_point(size = 4) +
  geom_smooth(method = 'lm', se = FALSE, color = 'grey30') +
  theme_publication(base_size = 24) +
  labs(x = 'Cohort strength connected metapopulation',
       y = 'Cohort strength isolated population') +
  xlim(c(-1.4,1.9)) +
  theme(legend.position = "none")

ggsave('./figures/cohortStrengthBKT.png', width = 11, height = 8, units='in')

CS_metaPopBKT <- lm(metaPop0 ~ metaPop1, data = cohortStrengthWideBKT %>% filter(cohort >= 2002))

summary(CS_metaPopBKT)


```

```{r dataIn}
write.csv(vB, file = './data/out/vB.csv')

# temporary fix - added 9/18/19, use this just to remake AIC1... fig
#vB[vB$tag == '0009f6f33c',]$cohort <- 2014  
#vB[vB$tag == '0009f6f404',]$cohort <- 2014

dataIn <- vB %>% filter(cohort %in% 2000:2013, species %in% speciesIn) %>%
  filter(!(cohort < 2002 & riverFactor %in% c('wb jimmy','wb mitchell','wb obear')))
```


Run to here to start

```{r raw data tables}

# get proportion of fish tagged for the first time as age0
dataAllSpp = vB %>% filter(cohort %in% 2000:2013, enc == 1) %>%
  filter(!(cohort < 2002 & riverFactor %in% c('wb jimmy','wb mitchell','wb obear'))) 

AIS <- dataAllSpp %>%
  group_by(tag) %>%
  summarise(minAIS = min(ageInSamples))
  
table(AIS$minAIS)/nrow(AIS)

# counts by season, year, spp
counts <- dataAllSpp %>%
  group_by(season, year, species) %>%
  summarize(n = n())
    
```


```{r raw data graphs}
# number of knots from gam 
kValue <- 9 # from mod6 below, just for graphing

# all fish
ggplot(vB %>% filter(cohort %in% 2000:2013), aes(ydayCumul,observedLength)) +
  geom_point(size = 0.5, alpha = 0.1) +
 # geom_smooth(span = 0.1, size = 1.5, se = F) +
  geom_smooth(method='gam', alpha = 0.1, formula=y~s(x, k = kValue), se = F) +
  theme_publication()

# by species
ggplot(vB %>% filter(cohort %in% 2000:2013), aes(ydayCumul,observedLength, color = species)) +
  geom_point(size = 0.5, alpha = 0.1) +
 # geom_smooth(span = 0.1, size = 1.5, se = F) +
  geom_smooth(method='gam', alpha = 0.1, formula=y~s(x, k = kValue), se = F) +
 # facet_grid(~species) +
  theme_publication()

ggplot(vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt', 'ats')), aes(ydayCumul,observedLength)) +
  geom_point(size = 0.5, alpha = 0.1) +
 # geom_smooth(span = 0.1, size = 1.5, se = F) +
 # geom_smooth(method='gam', alpha=0.1, formula=y~s(x, k = kValue), se = F) +
  labs(y = 'Observed body size (mm)',
       x = 'Days since age-0 Jan 1') +
  facet_wrap(~ speciesGG) +
  theme_publication(base_size = 20)

ggsave('./figures/rawBySpecies.png', width = 11, height = 8, units='in')

# by species (bkt, bnt), by cohort, by river gridded
ggplot(vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt', 'ats')), aes(ydayCumul,observedLength, group = species, color = (species))) +
  geom_point(size = 0.5, alpha = 0.1) +
 # geom_smooth(span = 0.1, size = 1.5, se = F) +
  geom_smooth(method='gam', alpha=0.1, formula=y~s(x, k = kValue), se = F) +
  facet_wrap( ~ cohort) +
  theme_publication()

# by species (bkt, bnt), by cohort, by river gridded
ggplot(vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt', 'ats')), aes(ydayCumul,observedLength, group = species, color = (species))) +
  geom_point(size = 0.5, alpha = 0.1) +
 # geom_smooth(span = 0.1, size = 1.5, se = F) +
  geom_smooth(method='gam', alpha=0.1, formula=y~s(x, k = kValue), se = F) +
  facet_grid(riverOrdered ~ cohort) +
  theme_publication()

```

```{r rivers where fish are fish}

ggplot(vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt', 'ats'), !is.na(observedLength)),
       aes(riverGG, fill = speciesGG)) +
  geom_bar() +
  labs(x = 'River', y = 'Number of observations', fill = 'Species') +
  theme_publication(base_size = 24) +
  scale_fill_grey() +
  theme(#legend.position = "right", 
    legend.direction = "vertical",
    legend.title = element_text(face = "plain"),
    legend.position=c(0.8, 0.8))
   
ggsave('./figures/rawCountsBySpecies.png', width = 11, height = 8, units='in')      

## Count Summaries
#number of observations
vB %>% 
  filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt', 'ats'), !is.na(observedLength)) %>%
  group_by( speciesGG) %>%
  summarize(n = n()) 

vB %>% 
  filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt', 'ats'), !is.na(observedLength)) %>%
  group_by(riverGG, speciesGG, year, season) %>%
  summarize(n = n()) %>%
  as.data.frame() %>%
  filter(season == 4)


#number of individuals
tags <- vB %>% 
  filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt', 'ats'), !is.na(observedLength)) %>%
  group_by(tag,species,metaPop01) %>%
  summarize(n = n())

tags %>% group_by(species) %>% summarise(n = n())
tags %>% group_by(species, metaPop01) %>% summarise(n = n())
```


```{r raw data histos}

ggplot(vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt'), river == "west brook"), aes(observedLength)) +
  geom_freqpoly(aes(color = species)) +
  theme_publication() +
  facet_grid(season ~ year)

# season 3
ggplot(vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt', 'bnt'), river == "west brook", season == 3), aes(observedLength)) +
  geom_freqpoly(aes(color = speciesGG), binwidth = 6, size = 1.35) +
  theme_publication() +
  theme(strip.text.x = element_text(size = 8), 
        strip.background = element_blank(),
        legend.title = element_text("Species"),
        legend.position = "right",
        legend.direction = "vertical") + 
  labs(color='Species') +
  scale_x_continuous("Fork Length (mm)", limits = c(49,200)) +
  scale_y_continuous("Count") +
  #scale_color_manual(values = c("lightblue", "lightgreen")) +
  scale_colour_brewer(palette = "Paired")+
  facet_wrap(~ year)

ggsave('./figures/season3freqpoly.png', width = 11, height = 8, units='in')

# 1 cohort
ggplot(vB %>% filter(cohort == 2009, species %in% c('bkt', 'bnt'), river == "west brook"), aes(observedLength)) +
  geom_freqpoly(aes(color = speciesGG), binwidth = 6, size = 1.35) +
  theme_publication() +
  theme(strip.text.x = element_text(size = 8), 
        strip.background = element_blank(),
        legend.title = element_text("Species"),
        legend.position = "right",
        legend.direction = "vertical") + 
  labs(color='Species') +
  scale_x_continuous("Fork Length (mm)", limits = c(49,200)) +
  scale_y_continuous("Count") +
  #scale_color_manual(values = c("lightblue", "lightgreen")) +
  scale_colour_brewer(palette = "Paired")+
  facet_grid(season ~ year)

ggsave('./figures/cohort2009freqpoly.png', width = 11, height = 8, units='in')

# across years
ggplot(vB %>% filter(cohort %in% 2000:2013,  species == 'bkt'), aes(observedLength)) +
 # geom_density(aes(color = factor(cohort)), size = 1.35) +
    geom_freqpoly(aes(color = factor(cohort)), binwidth = 8, size = 1.35) +
  theme_publication() +
  theme(strip.text.x = element_text(size = 8), 
        strip.background = element_blank(),
        legend.title = element_text("Species"),
        legend.position = "right",
        legend.direction = "vertical") + 
  labs(color = 'Cohort') +
  scale_x_continuous("Fork Length (mm)") +
  scale_y_continuous("Count") +
  #scale_color_manual(values = c("lightblue", "lightgreen")) +
  #scale_colour_brewer(palette = "Paired")+
  facet_grid(riverGG ~ ageInSamples, scales = 'free')
```

```{r length ageInSamples equals one}

ggplot(vB %>% filter(cohort %in% 2000:2013,  species == 'bnt', ageInSamples == 1), aes(yday,observedLength, color = factor(cohort))) + geom_point() + facet_grid(cohort~river)

ggplot(vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt','bnt'), ageInSamples == 1), aes(observedLength)) +
  geom_freqpoly(aes(group = cohort, color = cohort), binwidth = 7, size = 1.35) + 
  theme_publication(base_size = 20) +
  theme(
        #strip.text.x = element_text(size = 8), 
        #strip.background = element_blank(),
        #legend.title = element_text("Species"),
        legend.position = "right",
        legend.direction = "vertical"
        ) + 
  labs(color = 'Cohort') +
#  scale_color_grey(start = 0.15, end = 0.75) +
  scale_colour_gradient(low = "grey30", high = "grey90") +
  scale_x_continuous("Fork Length (mm)") +
  scale_y_continuous("Frequency") +
  facet_grid(speciesGG ~ riverGG)

ggsave('./figures/AIS1_freqpoly.png', width = 11, height = 8, units='in')

# length models for ageInSamples = 1 to look at variation within and among years/species/rivers
lenModBKT1 <- lm(observedLength ~  factor(cohort) * factor(riverGG), data = vB %>% filter(cohort %in% 2000:2013, species == 'bkt', ageInSamples == 1))
lenModBKT2 <- lm(observedLength ~  factor(cohort) + riverGG, data = vB %>% filter(cohort %in% 2000:2013,  species == 'bkt', ageInSamples == 1))

AIC(lenModBKT1,lenModBKT2) %>% rownames_to_column() %>% arrange(AIC)
summary(lenModBKT1)

anovaBKT <- anova(lenModBKT1)
lenModBKT1ss <- anovaBKT$"Sum Sq"
print(cbind(anovaBKT,PctExp=lenModBKT1ss/sum(lenModBKT1ss)*100))

###########################
meanCVLen <- 
vB %>% filter(cohort %in% 2000:2013, ageInSamples == 1) %>%
  group_by(species, riverGG, cohort) %>%
  summarize(meanL = mean(observedLength),
            sdL = sd(observedLength))

ggplot(meanCVLen, aes(meanL, sdL, color = factor(species))) +
  geom_point() +
  facet_wrap(~riverGG)

#no visual diff among rivers in relationship btw mean and cv in len
ggplot(meanCVLen, aes(meanL, sdL, color = riverGG)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm")


ggplot(meanCVLen, aes(meanL, sdL, color = factor(cohort))) +
  geom_point() +
  facet_wrap(~riverGG)

################################################
# compare mean lengths between trout
meansWide <- meanCVLen %>%
  select(-sdL) %>%
  pivot_wider(names_from = species, values_from = meanL) %>%
  filter(riverGG %in% c('West Brook', 'Open Large'))

ggplot(meansWide, aes(bkt, bnt)) +
  geom_point() +
  theme_publication() +
  scale_x_continuous('Brook Trout mean length (mm)') +
  scale_y_continuous('Brown Trout mean length (mm)', limits = c(60,90)) +
  geom_smooth(method = 'lm', color = 'black') +
  facet_wrap(~riverGG)

ggsave('./figures/AIS1_MeanLengthBKT_BNT.png', width = 11, height = 6, units='in')

#summary(lm(bnt ~ bkt, data = filter(meansWide, riverGG == 'West Brook')))
#summary(lm(bnt ~ bkt, data = filter(meansWide, riverGG == 'Open Large', bnt < 90)))
corr(meansWide %>% ungroup() %>% filter(riverGG == 'West Brook') %>% select(bkt, bnt) %>% drop_na())
corr(meansWide %>% ungroup() %>% filter(riverGG == 'Open Large', bnt < 90) %>% select(bkt, bnt) %>% drop_na())
#########################
#BNT
lenModBNT1 <- lm(observedLength ~  factor(cohort) * factor(riverGG), data = vB %>% filter(cohort %in% 2000:2013, species == 'bnt', ageInSamples == 1))
lenModBNT2 <- lm(observedLength ~  factor(cohort) + riverGG, data = vB %>% filter(cohort %in% 2000:2013,  species == 'bnt', ageInSamples == 1))
# lenModBNT3 <- lm(observedLength ~ 0 + factor(cohort) * riverGG + yday, data = vB %>% filter(cohort %in% 2000:2013,  species == 'bnt', ageInSamples == 1))
# lenModBNT4 <- lm(observedLength ~ 0 + factor(cohort) * riverGG + yday * riverGG, data = vB %>% filter(cohort %in% 2000:2013,  species == 'bnt', ageInSamples == 1))
# lenModBNT5 <- lm(observedLength ~ 0 + factor(cohort) * riverGG * yday, data = vB %>% filter(cohort %in% 2000:2013,  species == 'bnt', ageInSamples == 1))

AIC(lenModBNT1,lenModBNT2) %>% rownames_to_column() %>% arrange(AIC)
summary(lenModBNT1)
anovaBNT <- anova(lenModBNT1)
lenModBNT1ss <- anovaBNT$"Sum Sq"
print(cbind(anovaBNT,PctExp=lenModBNT1ss/sum(lenModBNT1ss)*100))

# both species together - use this for paper

lenMod1 <- lm(observedLength ~  factor(cohort) * factor(riverGG) * speciesGG, data = vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt','bnt'), ageInSamples == 1))
lenMod2 <- lm(observedLength ~  (factor(cohort) + factor(riverGG) + speciesGG)^2, data = vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt','bnt'), ageInSamples == 1))
lenMod3 <- lm(observedLength ~  factor(cohort) + factor(riverGG) + speciesGG, data = vB %>% filter(cohort %in% 2000:2013, species %in% c('bkt','bnt'), ageInSamples == 1))

AIC(lenMod1,lenMod2,lenMod3) %>% rownames_to_column() %>% arrange(AIC)

summary(lenMod1)
anova1 <- anova(lenMod1)
lenMod1ss <- anova1$"Sum Sq"
print(cbind(anova1,PctExp=lenMod1ss/sum(lenMod1ss)*100))

calc.relimp(lenMod3)
#                         lmg
# factor(cohort)  0.193090771
# factor(riverGG) 0.045329273
# speciesGG       0.000531708
```

```{r corr btw bkt/bnt mean lengths all samples}
meanCVLenAll <- 
#vB %>% filter(cohort %in% 2000:2013) %>% # leave out 2013 cohort - some bad cohort assignments I've asked Matt to check 8/4/2020
  vB %>% filter(cohort %in% 2000:2012) %>%
  group_by(species, riverGG, cohort, ageInSamples) %>%
  summarize(meanL = mean(observedLength),
            sdL = sd(observedLength))

################################################
# compare mean lengths between trout
meansWideAll <- meanCVLenAll %>%
  select(-sdL) %>%
  pivot_wider(names_from = species, values_from = meanL) %>%
  filter(riverGG %in% c('West Brook', 'Open Large'))

# get correlations
corrMod <- function(df) {
  df <- df %>% select(bkt, bnt) %>% drop_na()
  corr(df)
}

byAIS_River <- meansWideAll %>%
  group_by(riverGG, ageInSamples) %>%
  nest()

byAIS_River <- byAIS_River %>%
  mutate(corr = map(data, corrMod)) %>%
  unnest() %>%
  distinct(riverGG, ageInSamples, corr)

meansWideAll$AIS_labels <- factor(meansWideAll$ageInSamples, labels = c('Autumn, 0', 'Winter, 0', 'Spring, 1', 'Summer, 1', 'Autumn, 1', 'Winter, 1', 'Spring, 2', 'Summer, 2', 'Autumn, 2'))

byAIS_River$AIS_labels <- factor(byAIS_River$ageInSamples, labels = c('Autumn, 0', 'Winter, 0', 'Spring, 1', 'Summer, 1', 'Autumn, 1', 'Winter, 1', 'Spring, 2', 'Summer, 2', 'Autumn, 2'))

ggplot(meansWideAll, aes(bkt, bnt)) +
  geom_point() +
  theme_publication() +
  scale_x_continuous('Brook Trout mean length (mm)') +
  scale_y_continuous('Brown Trout mean length (mm)') +
  geom_smooth(method = 'lm', se = FALSE, color = 'black') +
  geom_abline(intercept = 0, slope = 1, color = 'grey') +
  geom_text(aes(label = round(corr, digits = 2), x = 95, y = 235), size = 3.5, data = byAIS_River) +
  facet_grid(riverGG ~ AIS_labels)

ggsave('./figures/AISALL_MeanLengthBKT_BNT.png', width = 11, height = 6, units='in')


```


```{r length at ageInSamples1 vs cohort strength}

# NO relationship between cohortStrengthScaled and meanLen for ageInSamples = 1 

ais1 <- vB %>% filter(cohort %in% 2000:2013, ageInSamples == 1) %>%
  group_by(speciesGG, metaPop01, cohort) %>%
  summarise(meanLen = mean(observedLength),
            meanYday = mean(yday))

cohortStrength2 <- cohortStrength
cohortStrength2$speciesGG <- factor(cohortStrength2$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)

cs_ais1 <- left_join(cohortStrength2,ais1)

# does mean size increase with day of year? No, but there are some early samples with yday < 255 that have small meanLen
ggplot(cs_ais1, aes(meanYday,meanLen, color = species)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE) +
  facet_grid(~ metaPop01)
summary(lm(meanLen ~ 0 + meanYday * species * factor(metaPop01), data = cs_ais1))

cs_ais1$metaPopLabel <- factor(cs_ais1$metaPop01, label = c("Isolated Large", "MetaPopulation"))

ggplot(cs_ais1 %>% filter(meanYday > 0, species %in% c('bkt','bnt')), aes(cohortStrengthScaled, meanLen)) +
  geom_point(aes(size = meanYday)) +
  geom_smooth(method = 'lm', se = FALSE, color = 'black') +
  theme_publication() +
  theme(strip.text.x = element_text(size = 8), 
        #strip.background = element_blank(),
        legend.title = element_text("Species"),
        legend.position = "right",
        legend.direction = "vertical") + 
  labs(color = 'Cohort') +
  scale_y_continuous("Mean Fork Length (mm)") +
  scale_x_continuous("Cohort Strength") +
  facet_grid(speciesGG ~ metaPopLabel)

ggsave('./figures/cohortStrengh_v_meanLenAIS1.png', width = 11, height = 8, units='in')


summary(lm(meanLen ~  cohortStrengthScaled * factor(metaPop01), data = cs_ais1 %>% filter(species == 'bkt')))

summary(lm(meanLen ~  cohortStrengthScaled, data = cs_ais1 %>% filter(species == 'bnt', metaPop01 == 1)))
```


```{r gam models - find best lm, before fitting detailed gams - only need to run for model selection}
# only including river, salmon01 becaseu we assume these have categorical effects

# not including season
# models with season have big dip in predictions for season 1. Season is...

mod2 <- bam(observedLength ~ riverFactor * factor(salmon01) + 
               s(ydayCumul, bs = 'cr'), 
               data = dataIn, 
               method = "REML")

mod4 <- bam(observedLength ~ riverFactor + 
               s(ydayCumul, bs = 'cr'), 
               data = dataIn, 
               method = "REML")

mod6 <- bam(observedLength ~ riverFactor + factor(salmon01) +
               s(ydayCumul, bs = 'cr'), 
               data = dataIn, 
               method = "REML")

AIC(mod2,mod4,mod6) %>% rownames_to_column() %>% arrange(AIC)
summary(mod6)
plot(mod6)
gam.check(mod6)

# bkt
#   rowname       df      AIC
# 1    mod6 14.82321 197082.8
# 2    mod2 25.99790 197663.0
# 3    mod4 13.96042 198350.4

#bnt
#   rowname       df       AIC
# 1    mod6 12.29048  98814.72
# 2    mod2 17.99609  99877.98
# 3    mod4 11.96329 100212.22

# need to run code at top of 'predictions' block before running this chunk
predGrid2 <- expand.grid(riverFactor = unique(dataIn$riverFactor),
                           ydayCumul = seq(250,1000, by = 10),
                           salmon01 = c(0,1),
                         season = 2) %>%
                    #left_join(., yDayAll) %>%
                    mutate()

pred2 <- predict(mod6, newdata = predGrid2)#, type = 'lpmatrix')

predGrid2 <- bind_cols(predGrid2, as.data.frame(pred2)) %>% mutate(pred = pred2, species = 'bkt')

ggplot(predGrid2 %>% filter(salmon01 == 0),
          
       aes(ydayCumul, pred)) +
  #geom_point() + 
  geom_vline(xintercept = c(365,365*2), color = 'grey60', linetype = 2) +
  geom_line(size = 1.1) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'Cohort') +
  scale_color_viridis_c(breaks = c(2000,2004,2008,2012), labels = c(2000,2004,2008,2012)) +
  theme_publication() +
  theme(legend.position = "right", 
        legend.direction = "vertical",
        legend.title = element_text(face = "plain")) +
  guides(color = guide_colorbar(barheight = 10,
                                barwidth = 1.5,
                                ticks = FALSE,
                                nbin = 100)) +
#  guide_legend(title = 'Cohort') +
  facet_wrap(~riverFactor)#, scales = 'free_y') 
 

```



```{r remove cohort, focus on spp-specific cohort strengths}
#sppoke with keith. decided focus on cohort is less interesting than river effects and density effects

mod1 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")
#summary(modCS3)
#plot(modCS3, pages = 8)

mod2 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               #s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")

mod3 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               #s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor),
              # s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")

mod4 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               #s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor),
              # s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
              # s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")

mod5 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) ,
               #s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
         #      s(cohort, bs = 'cr', k = kIn, by = riverFactor),
              # s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
              # s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")

mod6 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) ,
          #     s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               #s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
         #      s(cohort, bs = 'cr', k = kIn, by = riverFactor),
              # s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
              # s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")

mod7 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') ,
            #   s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) ,
          #     s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               #s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
         #      s(cohort, bs = 'cr', k = kIn, by = riverFactor),
              # s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
              # s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")

mod8 <- bam(observedLength ~ riverFactor + factor(salmon01) ,              
             #  s(ydayCumul, bs = 'cr') 
            #   s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) ,
          #     s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               #s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
         #      s(cohort, bs = 'cr', k = kIn, by = riverFactor),
              # s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
              # s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor), 
  #             s(cohortStrengthScaledATS2p5, bs = 'cr', k = kIn),
             data = dataIn, method = "REML")

AIC(mod1,mod2,mod3,mod4,mod5,mod6,mod7,mod8) %>% rownames_to_column() %>% arrange(AIC)
```


```{r best models for each species}

# Brook trout

modBKT <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor),
            
             data = vB %>% filter(cohort %in% 2000:2013, species %in% 'bkt'), method = "REML")

# modBKT2 <- bam(observedLength ~ riverFactor + factor(salmon01) +              
#                s(ydayCumul, bs = 'cr') +
#                s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
#                s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
#                s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
#                s(cohort, bs = 'cr', k = kIn, by = riverFactor) +
#                s(cohortStrengthScaledBKT,cohortStrengthScaledBNT2p5, k = kIn, by = riverFactor) ,
#             
#              data = vB %>% filter(cohort %in% 2000:2013, species %in% 'bkt'), method = "REML")
# 
# AIC(modBKT,modBKT2)

summary(modBKT)
#plot(modBKT, pages = 8, scale = 0)

predGridBKT <- expand.grid(riverFactor = unique(modBKT$model$riverFactor), 
                           cohortFactor = unique(modBKT$model$cohort),
                           ydayCumul = seq(250,1000, by = 14),
                           salmon01 = c(0,1),
                           cohortStrengthScaledBKT = seq(-2.5,2.5, by = 0.25),
                           cohortStrengthScaledBNT2p5 = seq(-2.5,2.5, by = 0.25)) %>%
                    #left_join(., yDayAll) %>%
                    mutate(cohortRiverFactor = paste(cohortFactor, riverFactor, sep = '_'),
                           cohort = cohortFactor) %>%
                    filter(!(cohort < 2002 & riverFactor %in% c('wb jimmy','wb mitchell','wb obear')))

predBKT <- predict(modBKT, newdata = predGridBKT)#, type = 'lpmatrix')

predGrid2BKT <- bind_cols(predGridBKT, as.data.frame(predBKT)) %>% mutate(pred = predBKT, species = 'bkt')

#################################
# Brown trout
# using CSr model becasue delta AIC is not huge btw it and CS3r. Better to have same models for both species

modBNT <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBNT2p5, bs = 'cr', k = kIn, by = riverFactor),
            
             data = vB %>% filter(cohort %in% 2000:2013, species %in% 'bnt'), method = "REML")

summary(modBNT)
#plot(modBNT,  pages = 8,scale = 0)

predGridBNT <- expand.grid(riverFactor = unique(modBNT$model$riverFactor), 
                           cohortFactor = unique(modBNT$model$cohort),
                           ydayCumul = seq(250,1000, by = 14),
                           salmon01 = c(0,1),
                           cohortStrengthScaledBKT = seq(-2.5,2.5, by = 0.25),
                           cohortStrengthScaledBNT2p5 = seq(-2.5,2.5, by = 0.25)) %>%
                    #left_join(., yDayAll) %>%
                    mutate(cohortRiverFactor = paste(cohortFactor, riverFactor, sep = '_'),
                           cohort = cohortFactor) %>%
                    filter(!(cohort < 2002 & riverFactor %in% c('wb jimmy','wb mitchell','wb obear')))

predBNT <- predict(modBNT, newdata = predGridBNT)#, type = 'lpmatrix')

predGrid2BNT <- bind_cols(predGridBNT, as.data.frame(predBNT)) %>% mutate(pred = predBNT, species = 'bnt')

##################
# combine species' predictions

predGrid2Both <- bind_rows(predGrid2BKT, predGrid2BNT) %>% dplyr:::select(-predBKT, -predBNT)

predGrid2Both$riverGG <- factor(predGrid2Both$riverFactor,
                         levels=c('west brook', 'wb jimmy', 'wb mitchell',"wb obear"),
                         labels = c("West Brook","Open Large","Open Small","Isolated Small"))
predGrid2Both$speciesGG <- factor(predGrid2Both$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"))

predGrid2Both <- predGrid2Both %>% filter(!(cohort < 2002 & riverFactor %in% c('wb jimmy','wb mitchell','wb obear')))

save(modBKT,modBNT,predBKT,predBNT,predGrid2Both, file = paste0('./data/out/bestModsBKTBNT.RData'))


appraise(modBKT)
ggsave('./figures/appraiseBKT.png', width = 11, height = 8, units='in')

appraise(modBNT)
ggsave('./figures/appraiseBNT.png', width = 11, height = 8, units='in')


```

```{r graphs of best models}
# load('./data/out/bestModsBKTBNT.RData')
source('./functions/plotGams.R')

# cohorts by river/species
ggplot(predGrid2Both %>% 
         filter(salmon01 ==0, cohortStrengthScaledBKT == 0, cohortStrengthScaledBNT2p5 == 0
#         (cohortStrengthScaledBKT == 0 & salmon01 == 0) | (cohortStrengthScaledBKT == 0 & cohortStrengthScaledBNT == 0 & cohortStrengthScaledATS == 0 & metaPop01 == 1 & salmon01 ==0)
           ),
#           cohortStrengthScaledBKT == 0, cohortStrengthScaledBNT == 0, cohortStrengthScaledATS == 0, metaPop01 == 1, salmon01 == 0),
       aes(ydayCumul, pred, group = cohort, color = cohort)) +
  #geom_point() + 
  geom_vline(xintercept = c(365,365*2), color = 'grey60', linetype = 2) +
  geom_line(size = 1.1) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'Cohort') +
  scale_color_viridis_c(breaks = c(2000,2004,2008,2012), labels = c(2000,2004,2008,2012)) +
  theme_publication(base_size = 20) +
  theme(legend.position = "right", 
        legend.direction = "vertical",
        legend.title = element_text(face = "plain")) +
  guides(color = guide_colorbar(barheight = 10,
                                barwidth = 1.5,
                                ticks = FALSE,
                                nbin = 100)) +
#  guide_legend(title = 'Cohort') +
  facet_grid(speciesGG ~ riverGG, scales = 'free_y') 
 
ggsave('./figures/predLengths14.png', width = 11, height = 8, units='in')

# specific spline effects by species
(plotCohort <- plotGamVarBySpecies(var = 's(cohort)', xAxisLab = 'Cohort'))
ggsave('./figures/cohortEffect.png', width = 8, height = 8, units='in')

(plotCohortStrength <- plotGamVarBySpecies(var = 's(cohortStrengthScaledBKT)', xAxisLab = 'Brook Trout cohort Strength'))
ggsave('./figures/cohortStrengthEffectBKT.png', width = 8, height = 8, units='in')

(plotCohortStrengthScaledBNT2p5 <- plotGamVarBySpecies(var = 's(cohortStrengthScaledBNT2p5)', xAxisLab = 'Brown Trout cohort Strength'))
ggsave('./figures/cohortStrengthEffectBNT.png', width = 8, height = 4.75, units='in')

#
#plot.gam(modBKT, pages = 10)

# plot specific predictions

# across rivers, by species
ggplot(predGrid2Both %>% 
         filter(salmon01 == 0, cohortStrengthScaledBKT == 0, cohort == 2006, cohortStrengthScaledBNT2p5 == 0, riverGG %in% c("West Brook", "Open Large")),
       aes(ydayCumul, pred, group = speciesGG)) +
  #geom_point() + 
  geom_vline(xintercept = c(365,365*2), color = 'grey60', linetype = 2) +
  geom_line(aes(linetype = speciesGG), size = 1.1) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'Cohort') +
#  scale_color_viridis_c() +
  theme_publication(base_size = 20) +
  #scale_color_grey() +
  theme(legend.position = "none", 
        legend.direction = "vertical",
        legend.title = element_text(face = "plain")) +
  facet_wrap(~ riverGG) 
 
ggsave('./figures/ydayCumulAcrossRiverBySpp.png', width = 8, height = 4.75, units='in')

# across species, by rivers
ggplot(predGrid2Both %>% 
         filter(salmon01 == 0, cohortStrengthScaledBKT == 0, cohort == 2006, cohortStrengthScaledBNT2p5 == 0),
       aes(ydayCumul, pred, group = riverGG, color = riverGG)) +
  #geom_point() + 
  geom_vline(xintercept = c(365,365*2), color = 'grey60', linetype = 2) +
  geom_line(size = 1.1) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'River') +
  #scale_color_viridis_c() +
  theme_publication(base_size = 20) +
  theme(legend.position = c(0.125, 0.8), 
        legend.direction = "vertical",
        legend.title = element_text(face = "plain")) +
  theme(legend.text=element_text(size=12),
        legend.title=element_text(size=12)) +
  facet_grid(cols = vars(speciesGG)) 

ggsave('./figures/ydayCumulAcrossSppByRiver.png', width = 8, height = 4.75, units='in')

# across bkt cohort strengths
ggplot(predGrid2Both %>% 
         filter(salmon01 == 0, cohort == 2006, cohortStrengthScaledBNT2p5 == 0),
       aes(ydayCumul, pred, group = cohortStrengthScaledBKT, color = cohortStrengthScaledBKT)) +
  #geom_point() + 
  geom_vline(xintercept = c(365,365*2), color = 'grey60', linetype = 2) +
  geom_line(size = 1.1) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'Brook Trout cohort strength') +
  #scale_color_viridis_c() +
  theme_publication(base_size = 20) +
  theme(legend.position = c(0.7, 0.37), 
        legend.direction = "vertical",
        legend.title = element_text(face = "plain")) +
  theme(legend.text = element_text(size = 10),
        legend.title = element_text(size = 16)) +
  facet_grid(riverGG ~ speciesGG) 

ggsave('./figures/ydayCumulAcrossCSBKTByRiver.png', width = 8, height = 4.75, units='in')

# across bnt cohort strengths
ggplot(predGrid2Both %>% 
         filter(salmon01 == 0, cohort == 2006, cohortStrengthScaledBKT == 0,
                riverGG %in% c('West Brook', 'Open Large')),
       aes(ydayCumul, pred, group = cohortStrengthScaledBNT2p5, color = cohortStrengthScaledBNT2p5)) +
  #geom_point() + 
  geom_vline(xintercept = c(365,365*2), color = 'grey60', linetype = 2) +
  geom_line(size = 1.1) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'Brown Trout cohort strength') +
  #scale_color_viridis_c() +
  theme_publication(base_size = 20) +
  theme(legend.position = c(0.7, 0.37), 
        legend.direction = "vertical",
        legend.title = element_text(face = "plain")) +
  theme(legend.text = element_text(size = 10),
        legend.title = element_text(size = 16)) +
  facet_grid(riverGG ~ speciesGG) 

ggsave('./figures/ydayCumulAcrossCSBNTByRiver.png', width = 8, height = 4.75, units='in')


# main spline over ydayCumul
plotBKT = plot.gam(modBKT, select = 1, scale = 0)
plotBNT = plot.gam(modBNT, select = 1, scale = 0)

plotBKTydayCumul <- data.frame(x = plotBKT[[1]]$x, y = plotBKT[[1]]$fit, se = plotBKT[[1]]$se) %>% mutate(species = 'bkt')
plotBNTydayCumul <- data.frame(x = plotBNT[[1]]$x, y = plotBNT[[1]]$fit, se = plotBNT[[1]]$se) %>% mutate(species = 'bnt')
plotBothydayCumul <- bind_rows(plotBKTydayCumul,plotBNTydayCumul) %>% mutate(upperCI = y + se * 1.96, lowerCI = y - se * 1.96)

plotBothydayCumul$speciesGG <- factor(plotBothydayCumul$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)

ggplot(plotBothydayCumul, aes(x, group = speciesGG)) + 
  geom_ribbon(aes( ymin = lowerCI, ymax = upperCI, fill  = speciesGG), alpha = 0.5) +
  geom_line(aes(y = y, linetype = speciesGG), size = 1.5) +
  scale_fill_manual(values = c('grey30', 'grey70')) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       linetype = 'Species') +
  theme_publication() +
  theme(legend.position = "right", 
        legend.direction = "vertical",
        legend.title = element_text(face="plain")) 

# river effects 
# BKT
plotBKTAll <- plot.gam(modBKT, page = 9)
plotBKTAll[[16]]$ylab # WB

plotBKTByRiver <- data.frame()
bktRiver1 <- 16
for(i in 1:4){
  ii <- i + bktRiver1 - 1
  tmp <- data.frame(x = plotBKTAll[[ii]]$x, y = plotBKTAll[[ii]]$fit, se = plotBKTAll[[i]]$se, ylab = plotBKTAll[[ii]]$ylab, riverIndex = i) %>% mutate(species = 'bkt', upperCI = y + se * 1.96, lowerCI = y - se * 1.96)
  plotBKTByRiver <- rbind(plotBKTByRiver, tmp)
}

#BNT
plotBNTAll <- plot.gam(modBNT, page = 6)
plotBNTAll[[16]]$ylab # WB

plotBNTByRiver <- data.frame()
bntRiver1 <- 16
for(i in 1:2){
  ii <- i + bntRiver1 - 1
  tmp <- data.frame(x = plotBNTAll[[ii]]$x, y = plotBNTAll[[ii]]$fit, se = plotBNTAll[[i]]$se, ylab = plotBNTAll[[ii]]$ylab, riverIndex = i) %>% mutate(species = 'bnt', upperCI = y + se * 1.96, lowerCI = y - se * 1.96)
  plotBNTByRiver <- rbind(plotBNTByRiver, tmp)
}

plotByRiver <- rbind(plotBKTByRiver, plotBNTByRiver)

plotByRiver$speciesGG <- factor(plotByRiver$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)
plotByRiver$riverGG <- factor(plotByRiver$riverIndex,
                         levels=c(1,2,3,4),
                         labels = c("West Brook","Open Large","Open Small","Isolated Small"))

ggplot(plotByRiver, aes(x)) +
  geom_line(aes(y = y, color = speciesGG), size = 1.5) +
  geom_ribbon(aes(ymin = lowerCI, ymax = upperCI, fill = speciesGG), alpha = 0.5, show.legend = FALSE) +
  scale_color_manual(values = c('grey30', 'grey70')) +
  scale_fill_manual(values = c('grey30', 'grey70')) +
  labs(y = 'Effect on body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'Species') +
  theme_publication() +
  theme(legend.position = "right", 
        legend.direction = "vertical",
        legend.title = element_text(face="plain")) +
  facet_wrap(~ riverGG)

ggsave('./figures/ydayCumulAcrossRiversBySpecies.png', width = 11, height = 8, units='in')



appraise(modBKT)


```








```{r mean lengths: from MS_Analysis_3spp_WB.Rmd. For Grenada talk}

# Has mean size changed over time?
means <- 
  cd %>% mutate( age = year - cohort ) %>%
    filter( riverOrdered == 'west brook', ageInSamples %in% 1:10, age < 3, year < 2016 ) %>%
    group_by(species,ageInSamples,year,season,age) %>%
    summarize(meanLen = mean(observedLength,na.rm = TRUE),
              sdLen = sd(observedLength,na.rm = TRUE),
              meanGR = mean(grLength,na.rm = TRUE),
              sdGR = sd(grLength,na.rm = TRUE)
              )

lenSlopes <- means %>%
  group_by( species, ageInSamples, season, age ) %>%
  nest()

lengthModel <- function(df){
  lm( meanLen ~ year, data = df )
}

grModel <- function(df){
  lm( meanGR ~ year, data = df )
}

lenSlopes <- lenSlopes %>%
  mutate( model = map(lenSlopes$data, lengthModel),
          modelGR = map(lenSlopes$data, grModel))

###################################
######### len here, gr below ######
lenSlopesTidy <- lenSlopes %>%
  mutate(glance = map(model, broom::tidy)) %>% 
  unnest(glance, .drop = TRUE) %>%
  filter(term == 'year') %>%
  mutate( sig = ifelse(p.value < 0.05,"*","")) %>%
  mutate( sig = ifelse(p.value < 0.001,"**",sig)) %>%
  mutate( sig = ifelse(p.value < 0.0001,"***",sig))


means$seasonGG <- factor(means$season, levels = 1:4, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
means$speciesGG <- factor(means$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)
lenSlopesTidy$seasonGG <- factor(lenSlopesTidy$season, levels = 1:4, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
lenSlopesTidy$speciesGG <- factor(lenSlopesTidy$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)

ggplot( means %>% filter(year >= 2000, species != 'ats'), aes(year,meanLen, group= speciesGG)) +
  geom_point( aes(color = speciesGG), size = 4) +
  geom_smooth( aes(color = speciesGG), se = FALSE, method = 'lm') +
  labs( x = "Year", y = "Mean body length (mm)" ) +

  geom_text(data = lenSlopesTidy %>% filter(species == 'bkt', age<2), 
            aes(x=2000,y=225, label=paste(round(estimate,2),sig)),hjust = 0, size = 6)+#, color = speciesGG)) +
  geom_text(data = lenSlopesTidy %>% filter(species == 'bnt', age<2), 
            aes(x=2000,y=195, label=paste(round(estimate,2),sig)),hjust = 0, size = 6)+#, color = speciesGG)) +

  geom_text(data = lenSlopesTidy %>% filter(species == 'bkt', age==2), 
            aes(x=2011.8,y=104, label=paste(round(estimate,2),sig)),hjust = 0, size = 6)+#, color = speciesGG)) +
  geom_text(data = lenSlopesTidy %>% filter(species == 'bnt', age==2), 
            aes(x=2011.8,y=74, label=paste(round(estimate,2),sig)),hjust = 0, size = 6)+

  theme_publication(base_size = 24) +
  theme(legend.title = element_text("Species"),
      #  legend.position = "right",
     #   legend.direction = "vertical"
        legend.position = "bottom",
        legend.direction = "horizontal") + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) +
  facet_grid(seasonGG ~ age, scales='free')

ggsave('./figures/meanSizes.png', width = 11, height = 11, units='in')

# one season/year only
ggplot( means %>% filter(year >= 2000, species != 'ats', ageInSamples == 8), aes(year,meanLen, group= speciesGG)) +
  geom_point( aes(color = speciesGG), size = 4) +
  geom_smooth( aes(color = speciesGG), se = FALSE, method = 'lm') +
  labs( x = "Year", y = "Mean body length (mm)" ) +
  theme_publication(base_size = 24) +
  theme(legend.title = element_text("Species"),
      #  legend.position = "right",
     #   legend.direction = "vertical"
                legend.position = "bottom",
        legend.direction = "horizontal") + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) +
  facet_grid(seasonGG ~ age)
ggsave('./figures/meanSizesAIS_1.png', width = 11, height = 8, units='in')

# is a model with salmon presence absence better than a year model?
means$ats01 <- ifelse(means$year <= 2005, 1, 0)

modMeans1 = lm(meanLen ~ year * species, data = means %>% filter(year >= 2000, species != 'ats', ageInSamples == 1))
modMeans2 = lm(meanLen ~ year * factor(ats01) * species, data = means %>% filter(year >= 2000, species != 'ats', ageInSamples == 1))
modMeans3 = lm(meanLen ~ factor(ats01) * species, data = means %>% filter(year >= 2000, species != 'ats', ageInSamples == 1))
modMeans4 = lm(meanLen ~ factor(ats01)*year, data = means %>% filter(year >= 2000, species != 'ats', ageInSamples == 1))
AIC(modMeans1, modMeans2, modMeans3, modMeans4)

# one season/year only
ggplot( means %>% filter(year >= 2000, species != 'ats', ageInSamples == 1), aes(year,meanLen, group= speciesGG)) +
  geom_point( aes(color = speciesGG), size = 4) +
  geom_smooth( aes(group = factor(ats01)), color = 'black', se = FALSE, method = 'lm') +
  labs( x = "Year", y = "Mean body length (mm)" ) +
  theme_publication(base_size = 24) +
  theme(legend.title = element_text("Species"),
      #  legend.position = "right",
     #   legend.direction = "vertical"
        legend.position = "bottom",
        legend.direction = "horizontal") + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) +
  facet_grid(seasonGG ~ age)

ggsave('./figures/meanSizesAIS_1_ats01.png', width = 11, height = 8, units='in')



# mean increases 
lenSlopesTidy %>%
  filter(species != 'ats') %>%
  summarise( means = mean(estimate),
             sd = sd(estimate))

# mean increases by species
lenSlopesTidy %>%
  group_by(species) %>%
  summarise( means = mean(estimate),
             sd = sd(estimate))

# do increases (slopes) increase over age? Yes
ggplot(lenSlopesTidy %>% filter(species != 'ats'), aes((ageInSamples),estimate, color=speciesGG)) +
  geom_point(size = 5) +
  geom_smooth(method='lm', se=FALSE, size = 1.5) +
  scale_x_continuous(breaks = 1:10, labels = c('0 Fall','0 Winter','1 Spring','1 Summer','1 Fall','1 Winter','2 Spring','2 Summer','2 Fall','2 Winter')) +
  labs( x = "Age Season", y = "Slope of mean body length over years" ) +
  theme_publication(base_size = 24) +
  theme(legend.title = element_text("Species"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 40, hjust = 1)) + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) 

ggsave(paste0('figures/meanLengthsOverAge.png'), width = 11, height = 10, units='in')

# species diff in increases in length?
sppEffect <- (lm(estimate ~ ageInSamples * (species), data = lenSlopesTidy))
summary(sppEffect)
anova(sppEffect)

# mean diff in slopes btw bkt and bnt
lenSlopesTidy %>%
  filter(species != 'ats') %>%
  group_by(species) %>%
  summarise(means = mean(estimate))

#####################################  
#################################
# growth rate
grSlopesTidy <- lenSlopes %>%
  mutate(glance = map(modelGR, broom::tidy)) %>% 
  unnest(glance, .drop = TRUE) %>%
  filter(term == 'year') %>%
  mutate( sig = ifelse(p.value < 0.05,"*","")) %>%
  mutate( sig = ifelse(p.value < 0.001,"**",sig)) %>%
  mutate( sig = ifelse(p.value < 0.0001,"***",sig))

##
means$seasonGG <- factor(means$season, levels = 1:4, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
means$speciesGG <- factor(means$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)
grSlopesTidy$seasonGG <- factor(grSlopesTidy$season, levels = 1:4, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
grSlopesTidy$speciesGG <- factor(grSlopesTidy$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)

ggplot( means %>% filter(year >= 2000, species != 'ats'), aes(year,meanGR, group= speciesGG)) +
  geom_point( aes(color = speciesGG), size = 4) +
  geom_smooth( aes(color = speciesGG), se = FALSE, method = 'lm') +
  labs( x = "Year", y = "Mean growth rate (mm/d)" ) +
  geom_text(data = grSlopesTidy %>% filter(species == 'bkt', age<2), 
            aes(x=2000,y=0.68, label=paste(round(estimate,4),sig)),hjust = 0, size = 6)+#, color = speciesGG)) +
  geom_text(data = grSlopesTidy %>% filter(species == 'bnt', age<2), 
            aes(x=2000,y=0.55, label=paste(round(estimate,4),sig)),hjust = 0, size = 6)+#, color = speciesGG)) +

  geom_text(data = grSlopesTidy %>% filter(species == 'bkt', age==2), 
            aes(x=2011.5,y=0.64, label=paste(round(estimate,4),sig)),hjust = 0, size = 6)+#, color = speciesGG)) +
  geom_text(data = grSlopesTidy %>% filter(species == 'bnt', age==2), 
            aes(x=2011.5,y=0.51, label=paste(round(estimate,4),sig)),hjust = 0, size = 6)+
  theme_publication(base_size = 24) +
  theme(legend.title = element_text("Species"),
      #  legend.position = "right",
     #   legend.direction = "vertical"
        legend.position = "bottom",
        legend.direction = "horizontal") + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) +
  facet_grid(seasonGG~age)

ggsave('./figures/meanGRs.png', width = 11, height = 11, units='in')

# mean increases 
grSlopesTidy %>%
  filter(species != 'ats') %>%
  summarise( means = mean(estimate),
             sd = sd(estimate))

# mean increases by species
grSlopesTidy %>%
  group_by(species) %>%
  summarise( means = mean(estimate),
             sd = sd(estimate))

# do increases (slopes) increase over age? Yes
ggplot(grSlopesTidy %>% filter(species != 'ats'), aes((ageInSamples),estimate, color=speciesGG)) +
  geom_point(size = 5) +
  geom_smooth(method='lm', se=FALSE) +  
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = 1:10, labels = c('0 Fall','0 Winter','1 Spring','1 Summer','1 Fall','1 Winter','2 Spring','2 Summer','2 Fall','2 Winter')) +
  labs( x = "Age Season", y = "Slope of mean growth rate over years" ) +
  theme_publication(base_size = 24) +
  theme(legend.title = element_text("Species"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 40, hjust = 1)) + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) 

ggsave('./figures/meanGRsOverAge.png', width = 11, height = 11, units='in')

summary(lm(estimate~ageInSamples, data = grSlopesTidy %>% filter(species=='bkt')))
summary(lm(estimate~ageInSamples, data = grSlopesTidy %>% filter(species=='bnt')))

# species diff in increases in gr?
sppEffectGR <- (lm(estimate ~ ageInSamples * (species), data = grSlopesTidy))
summary(sppEffectGR)
anova(sppEffectGR)

# mean diff in slopes btw bkt and bnt
grSlopesTidy %>%
  filter(species != 'ats') %>%
  group_by(species) %>%
  summarise(means = mean(estimate))




```

```{r size-dep imm or mort? For Spain talk}

### for losses

cd01 <-  cd %>%
  filter(knownZ == 1) %>%
  group_by(tagIndex) %>%
  mutate(first = min(sampleNumber),
         firstObs = sampleNumber == first,
         last = max(sampleNumber),
         lastObs = sampleNumber == last,
         notLastObs = !lastObs,
         nObs = n(),
         age = year - cohort
  ) %>%
  ungroup()

meansByAIS <- cd01 %>%
  group_by(species, ageInSamples, cohort, river) %>%
  summarise(meanLen = mean(observedLength, na.rm =T),
            sdLen = sd(observedLength, na.rm = T),
            n = n())
cd01 <- left_join(cd01, meansByAIS) %>%
  mutate(observedLengthStd = (observedLength - meanLen) / sdLen,
         cohortStd = cohort - 2007)

#cd %>% select(tagIndex,sampleNumber, firstObs,lastObs, knownZ, observedLength) %>% head(50) %>% as.data.frame()
cd01Mod <- cd01 %>% filter(species %in% c('bkt', 'bnt'), river == 'west brook', ageInSamples %in% 1:10, cohort %in% 2000:2014)

ggplot(cd01Mod, aes(observedLengthStd, notLastObs*1, color = factor(species), group = factor(species))) +
  geom_point(alpha = 0.01) +
  geom_smooth(method = "glm", 
    method.args = list(family = "binomial"), 
    se = FALSE) +
 # scale_color_viridis_c() +
  facet_wrap( ~ cohort, scales = 'free')

#### by species and ageInSamples

sensSlopes <- cd01Mod %>%
  group_by( species, ageInSamples ) %>%
  nest()

survModel <- function(df){
  glm(notLastObs*1 ~ observedLengthStd + cohortStd, family = 'binomial', data = df )
}
enterModel <- function(df){
  glm(firstObs*1 ~ observedLengthStd + cohortStd, family = 'binomial', data = df )
}

sensSlopes <- sensSlopes %>%
  mutate(modelSurv = map(sensSlopes$data, survModel),
         modelEnter = map(sensSlopes$data, enterModel))

sensSlopesTidy <- sensSlopes %>%
  mutate(surv = map(modelSurv, broom::tidy),
         enter = map(modelEnter, broom::tidy)) %>% 
  unnest(surv, enter, .drop = TRUE) %>%
  filter(term == 'cohortStd') %>% # cohort effect
  rename(estimateSurv = estimate, estimateEnter = estimate1) %>%
  select(species,ageInSamples,estimateSurv, estimateEnter) #%>%
  #gather("type", "estimate", estimateSurv:estimateEnter)

ggplot(sensSlopesTidy, aes(ageInSamples, estimate, color = type)) +
  geom_point() +
  geom_line() +
  facet_wrap(~species)

```

```{r dummy graphs for Spain talk}

sizesForGraph <- data.frame(year = c(2000,2015), surv = c(100, 150))
ggplot(sizesForGraph, aes(year,surv)) +
  geom_line(size = 2) +
  labs(x = 'Year', y = 'Mean body length (mm)') +
  ylim(80,200) +
  theme_publication(base_size = 36)
ggsave('./figures/sizesDummy.png', width = 11, height = 11, units='in')


survForGraph <- data.frame(size = c(-2,2), surv = c(0.25,0.75))
ggplot(survForGraph, aes(size,surv)) +
  geom_line(size = 2) +
  labs(x = 'Standardized length', y = 'Probability of seen again') +
  theme_publication(base_size = 36)
ggsave('./figures/pSurvivalDummy.png', width = 11, height = 11, units='in')

firstForGraph <- data.frame(size = c(-2,2), surv = c(0.35,0.65))
ggplot(firstForGraph, aes(size,surv)) +
  geom_line(size = 2) +
  labs(x = 'Standardized length', y = 'Probability of first observation') +
  theme_publication(base_size = 36)
ggsave('./figures/pFirstDummy.png', width = 11, height = 11, units='in')


sizesForGraph <- data.frame(year = c(2000,2015), surv = c(100, 150))
ggplot(sizesForGraph, aes(year,surv)) +
  geom_line(size = 3) +
  labs(x = 'Year', y = 'Mean body length (mm)') +
  ylim(80,200) +
  theme_publication(base_size = 36)
ggsave('./figures/sizesDummy.png', width = 11, height = 11, units='in')

#### show interactions

survForGraph <- data.frame(ind = c(1,1,2,2,3,3), size = c(-2,2), surv = c(0.52,0.55,0.51,0.24,0.54,0.82))
ggplot(survForGraph, aes(size,surv, group = ind)) +
  geom_line(size = 2) +
  labs(x = 'Standardized length', y = 'Probability of seen again') +
  theme_publication(base_size = 36)
ggsave('./figures/pSurvivalDummy3.png', width = 11, height = 11, units='in')

firstForGraph <- data.frame(ind = c(1,1,2,2,3,3), size = c(-2,2), surv = c(0.42,0.45,0.41,0.14,0.44,0.72))
ggplot(firstForGraph, aes(size,surv, group = ind)) +
  geom_line(size = 2) +
  labs(x = 'Standardized length', y = 'Probability of first observation') +
  theme_publication(base_size = 36)
ggsave('./figures/pFirstDummy3.png', width = 11, height = 11, units='in')



```

```{r get betas from growth model for sensitivities}
load("D:/projects/linkedModels/data/out/allBetas.RData") #loads df 'q'
qFig1 <- q %>% filter(riverGG == 'WB', species %in% c('bkt','bnt'))
qFig1$season <- as.numeric(as.character(qFig1$season))
qFig1$isYOY <- as.numeric(as.character(qFig1$isYOY))
qFig <- qFig1 %>%
  mutate( varText = tolower(betaGG)) %>%
  mutate( varText = ifelse(varText == 'temp*flow','temp:flow', varText)) %>%
  mutate( varText = ifelse(varText == 'bnt*bkt','bkt:bnt', varText)) %>%
  select(isYOY,season,species,median,varText)
qFig$seasonGG <- factor(qFig$season, levels = 1:4, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
#get slopes of env variables

load('D:/projects/linkedModels/data/out/flowSlopesTidy.RData')
flowSlopesTidy2 <- flowSlopesTidy %>% filter(riverOrderedGG == 'West Brook') %>% select(estimate, seasonGG) %>% mutate(varText = 'flow')
load('D:/projects/linkedModels/data/out/tempSlopesTidy.RData')
tempSlopesTidy2 <- tempSlopesTidy %>% filter(riverOrderedGG == 'West Brook') %>% select(estimate, seasonGG) %>% mutate(varText = 'temp')
load('D:/projects/linkedModels/data/out/nSlopesTidy.RData')
nSlopesTidy2 <- nSlopesTidy %>% select(estimate, season, species) %>% mutate(varText = species)
nSlopesTidy2$seasonGG <- factor(nSlopesTidy2$season, levels = 1:4, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
nSlopesTidy2 <- nSlopesTidy2 %>% select(estimate,seasonGG,varText)

allSlopesTidy <- bind_rows(nSlopesTidy2, tempSlopesTidy2, flowSlopesTidy2)

allSlopesTidyWBetas <- left_join(qFig, allSlopesTidy, by = c('seasonGG', 'varText')) %>% mutate(sens = median * estimate)

ggplot(allSlopesTidyWBetas%>%filter(!is.na(sens), varText != 'ats'), aes(seasonGG, sens, color = varText)) +
  geom_point() +
  facet_grid(species + isYOY ~ varText, scales = 'free')
```


```{r }
############# 1st attempt at imm em
mod1 <- glm(notLastObs*1 ~ observedLengthStd * cohortStd * species * factor(ageInSamples), family = 'binomial', data = cd01Mod)
#mod2 <- glm(notLastObs*1 ~ observedLengthStd * factor(cohortStd) * species * factor(ageInSamples), family = 'binomial', data = cd01Mod)
mod3 <- glm(notLastObs*1 ~ observedLengthStd * species * factor(ageInSamples), family = 'binomial', data = cd01Mod)

AIC(mod1,mod3)

summary(mod1)
anova(mod1, test="Chi")

pred <- expand.grid(observedLengthStd = seq(-2,2, length.out = 50), cohortStd = unique(cd01Mod$cohortStd), species = c('bkt', 'bnt'), ageInSamples = unique(cd01Mod$ageInSamples))
  
pred$pred <- predict.glm(mod1, newdata = pred, type = 'response')

u <- cd01Mod %>% distinct(age, season, ageInSamples) %>% arrange(ageInSamples) %>% filter(!(age==2 & ageInSamples == 6))
pred <- left_join(pred, u)

pred$seasonGG <- factor(pred$season, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
pred$cohort <- pred$cohortStd + 2007
pred$speciesGG <- factor(pred$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)

ggplot(pred, aes(observedLengthStd, pred, color = (cohortStd), group = (cohortStd))) +
  geom_point() +
  scale_color_viridis_c() +
  scale_y_continuous("Probability of survival") +
  facet_grid(species ~ ageInSamples, scales = 'free')

ggplot(pred %>% filter(cohortStd %in% 0, age < 3), aes(observedLengthStd, pred, color = speciesGG)) +
  geom_point(size = 2) +
  scale_x_continuous("Standardized length") +
  scale_y_continuous(lim = c(0,1),"Probability of seen again") +
  theme_publication(base_size = 28) +
  theme(legend.title = element_text("Species"),
        legend.position = "bottom",
        legend.direction = "horizontal"
        ) + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) +
  facet_grid(seasonGG ~ age)

ggsave('./figures/pSurvival.png', width = 11, height = 11, units='in')



################################
# gains - immigration, firstObs

ggplot(cd01Mod, aes(observedLengthStd, firstObs*1, color = factor(species), group = factor(species))) +
  geom_jitter(alpha = 0.1) +
  geom_smooth(method = "glm", 
    method.args = list(family = "binomial"), 
    se = FALSE) +
 # scale_color_viridis_c() +
  xlim(c(-2.75,2.75)) +
  facet_grid(ageInSamples ~ cohort)

ggplot(cd01Mod%>%filter(ageInSamples == 3), aes(observedLengthStd, firstObs*1, color = factor(species), group = factor(species))) +
  geom_jitter(alpha = 0.1) +
  geom_smooth(method = "glm", 
    method.args = list(family = "binomial"), 
    se = FALSE) +
 # scale_color_viridis_c() +
  xlim(c(-2.75,2.75)) +
  facet_wrap( ~ cohort)

modi1 <- glm(firstObs*1 ~ observedLengthStd * cohortStd * species * factor(ageInSamples), family = 'binomial', data = cd01Mod)
modi2 <- glm(firstObs*1 ~ observedLengthStd * species * factor(ageInSamples), family = 'binomial', data = cd01Mod)
modi3 <- glm(firstObs*1 ~ observedLengthStd * species , family = 'binomial', data = cd01Mod)
modi4 <- glm(firstObs*1 ~ observedLengthStd * factor(ageInSamples), family = 'binomial', data = cd01Mod)
modi5 <- glm(firstObs*1 ~ observedLengthStd, family = 'binomial', data = cd01Mod)

AIC(modi1,modi2,modi3,modi4,modi5) %>% rownames_to_column() %>% arrange(AIC)

summary(modi1)
anova(modi1, test="Chi")
###
predi <- expand.grid(observedLengthStd = seq(-2,2, length.out = 50), cohortStd = unique(cd01Mod$cohortStd), species = c('bkt', 'bnt'), ageInSamples = unique(cd01Mod$ageInSamples))
  
predi$pred <- predict.glm(modi1, newdata = predi, type = 'response')

u <- cd01Mod %>% distinct(age, season, ageInSamples) %>% arrange(ageInSamples) %>% filter(!(age==2 & ageInSamples == 6))
predi <- left_join(predi, u)

ggplot(predi, aes(observedLengthStd, pred, color = (cohortStd), group = (cohortStd))) +
  geom_point() +
  scale_color_viridis_c() +
  scale_y_continuous("Probability of first observation") +
  facet_grid(species ~ ageInSamples, scales = 'free')

predi$seasonGG <- factor(predi$season, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
predi$cohort <- predi$cohortStd + 2007
predi$speciesGG <- factor(predi$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)

ggplot(predi %>% filter(cohortStd %in% c(0), species == 'bkt', age < 3), aes(observedLengthStd, pred)) +
  geom_point() +
  scale_color_viridis_c() +
  scale_x_continuous("Standardized length") +
  scale_y_continuous(lim = c(0,1),"Probability of first observation") +
  theme_publication() +
  facet_grid(seasonGG ~ age)

ggplot(predi %>% filter(cohortStd %in% c(0), age < 3), aes(observedLengthStd, pred, color = speciesGG)) +
  geom_point(size = 2) +
  scale_x_continuous("Standardized length") +
  scale_y_continuous(lim = c(0,1),"Probability of first observation") +
  theme_publication(base_size = 28) +
  theme(legend.title = element_text("Species"),
        legend.position = "bottom",
        legend.direction = "horizontal"
        ) + 
  labs(color='Species') +
  scale_color_grey(start = 0.15, end = 0.75) +
  facet_grid(seasonGG ~ age)

ggsave('./figures/pFirstObs.png', width = 11, height = 11, units='in')
```







```{r models with no fixed season effects or categories for splines}

system.time(
mod6_YDCcr_Cr_CSr_Tr_Fr_TFr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = riverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = riverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = riverFactor), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr_Cr_CSr_T_F_TF <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr_Cr_CS_T_F_TF <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr_C_CS_T_F_TF <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDC_C_CS_T_F_TF <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(cohort, bs = 'cr', k = kIn) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn), 
               data = dataIn, 
               method = "REML")
)

AIC(mod6_YDC_C_CS_T_F_TF,mod6_YDCcr_C_CS_T_F_TF,mod6_YDCcr_Cr_CS_T_F_TF,mod6_YDCcr_Cr_CSr_T_F_TF,mod6_YDCcr_Cr_CSr_Tr_Fr_TFr)  %>% rownames_to_column() %>% arrange(AIC)

summary(mod6_YDCcr_Cr_CSr_Tr_Fr_TFr)
plot(mod6_YDCcr_Cr_CSr_Tr_Fr_TFr, pages = 8, shade = TRUE, scale = 0)


#BKT
#                       rowname        df      AIC
# 1 mod6_YDCcr_Cr_CSr_Tr_Fr_TFr 194.27159 402517.3
# 2    mod6_YDCcr_Cr_CSr_T_F_TF 178.16547 402696.5
# 3     mod6_YDCcr_Cr_CS_T_F_TF 170.29804 403228.7
# 4      mod6_YDCcr_C_CS_T_F_TF 166.30172 404261.2
# 5        mod6_YDC_C_CS_T_F_TF  29.89126 412576.2

#BNT
#                       rowname        df      AIC
# 1 mod6_YDCcr_Cr_CSr_Tr_Fr_TFr 102.82522 225950.4
# 2    mod6_YDCcr_Cr_CSr_T_F_TF  98.12051 225974.0
# 3     mod6_YDCcr_Cr_CS_T_F_TF  96.51127 225994.7
# 4      mod6_YDCcr_C_CS_T_F_TF  92.93128 226010.4
# 5        mod6_YDC_C_CS_T_F_TF  27.97005 231079.5

```

```{r models without T and F}
# Not sure how to get models with season-specific T and F effects to work within season without messing up predictions. # Leave T and F out and focus on densities

mod6_YDCcr_Cr_CSr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor),  # this is conspecific cS only
               data = dataIn, 
               method = "REML")

system.time(
mod6_YDCcr_Cr_CS3r <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledBNT, bs = 'cr', k = kIn, by = riverFactor) +
               s(cohortStrengthScaledATS, bs = 'cr', k = kIn, by = riverFactor),  
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr_Cr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor),  
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor),  
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDC <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr'),  
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr_Cr_CSBKTr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaledBKT, bs = 'cr', k = kIn, by = riverFactor),  
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr_Cr_CSBNTr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaledBNT, bs = 'cr', k = kIn, by = riverFactor),  
               data = dataIn, 
               method = "REML")
)

system.time(
mod6_YDCcr_Cr_CSATSr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaledATS, bs = 'cr', k = kIn, by = riverFactor),  
               data = dataIn, 
               method = "REML")
)


AIC(mod6_YDCcr_Cr_CSr, mod6_YDCcr_Cr_CS3r, mod6_YDCcr_Cr_CSBKTr, mod6_YDCcr_Cr_CSBNTr, mod6_YDCcr_Cr_CSATSr, mod6_YDCcr_Cr,mod6_YDCcr,mod6_YDC)  %>% rownames_to_column() %>% arrange(AIC)

summary(mod6_YDCcr_Cr_CSr)
plot(mod6_YDCcr_Cr_CS3r, pages = 7, shade = TRUE, scale = 0)

# bkt
#                rowname        df      AIC
# 1    mod6_YDCcr_Cr_CSr 173.85954 413790.2
# 2   mod6_YDCcr_Cr_CS3r 188.68933 415278.2
# 3 mod6_YDCcr_Cr_CSBKTr 167.72761 416582.2
# 4 mod6_YDCcr_Cr_CSBNTr 168.43917 417098.5
# 5 mod6_YDCcr_Cr_CSATSr 167.84300 417569.6
# 6        mod6_YDCcr_Cr 160.60559 417764.7
# 7           mod6_YDCcr 149.80639 420935.0
# 8             mod6_YDC  14.99337 429769.2

# bnt
#                rowname       df      AIC
# 1   mod6_YDCcr_Cr_CS3r 96.91663 231844.1
# 2    mod6_YDCcr_Cr_CSr 84.99160 231875.4
# 3 mod6_YDCcr_Cr_CSBKTr 84.39999 232019.6
# 4 mod6_YDCcr_Cr_CSBNTr 87.25717 232120.2
# 5 mod6_YDCcr_Cr_CSATSr 85.68893 232203.3
# 6        mod6_YDCcr_Cr 81.27554 232235.7
# 7           mod6_YDCcr 75.00492 233885.5
# 8             mod6_YDC 12.99685 238636.2
```


```{r predictions}

ydayCumulSeason <- distinct(dataIn, ydayCumul,season,age) %>% arrange(ydayCumul) %>% mutate(age_season = paste(age,season,sep = '_')) %>%
  group_by(age_season) %>% summarise(age=min(age),season=min(season),minY=min(ydayCumul),maxY=max(ydayCumul))
#38 obear fish were captured in january, but get season 4 and are age 1, so have very small ydayCumul -need to manually reset 
#dataIn %>% filter(age==1,season==4,ydayCumul==367) %>% select(tag,cohort,detectionDate,year,ydayCumul,yday,river,age,season)
ydayCumulSeason$minY <- ifelse(ydayCumulSeason$age_season == '1_4',670,ydayCumulSeason$minY)
ydayCumulSeason$minY <- ifelse(ydayCumulSeason$age_season == '2_4',1035,ydayCumulSeason$minY)
ydayCumulSeason$minY <- ifelse(ydayCumulSeason$age_season == '0_3',0,ydayCumulSeason$minY)
ydayCumulSeason %>% mutate(minY2 = lead(minY))

yDayAll <- data.frame(ydayCumul = 250:1000)
yDayAll$season <- NA

# fill in season for each day of the year (yDayAll) based on ydayCumulSeason min values
# need this to get season into all ydayCumul in predGridBKT
for(i in 1:nrow(yDayAll)) {
  for(j in 1:(nrow(ydayCumulSeason) - 1)) {
    if (between(yDayAll$ydayCumul[i], ydayCumulSeason$minY[j], ydayCumulSeason$minY[j + 1])) {
      yDayAll$season[i] <- ydayCumulSeason$season[j]
    }
  }
}

predGrid <- expand.grid(riverFactor = unique(dataIn$riverFactor), 
                        cohortFactor = unique(dataIn$cohort),
                        ydayCumul = seq(250,1000, by = 10),
                        salmon01 = c(0,1),
                        cohortStrengthScaled = seq(-2.5,2.5, by = 0.25)) %>%
                    #left_join(., yDayAll) %>%
                    mutate(cohortRiverFactor = paste(cohortFactor, riverFactor, sep = '_'),
                           cohort = cohortFactor) 


pred <- predict(mod6_YDCcr_Cr_CSr, newdata = predGrid)#, type = 'lpmatrix')

predGrid2 <- bind_cols(predGrid, as.data.frame(pred)) %>% mutate(pred = pred)

ggplot(predGrid2 %>% filter(salmon01 == 0, cohortStrengthScaled == 0),
          
       aes(ydayCumul, pred, group = cohort, color = cohort)) +
  #geom_point() + 
  geom_vline(xintercept = c(365,365*2), color = 'grey60', linetype = 2) +
  geom_line(size = 1.1) +
  labs(y = 'Predicted body size (mm)',
       x = 'Days since age-0 Jan 1',
       color = 'Cohort') +
  scale_color_viridis_c(breaks = c(2000,2004,2008,2012), labels = c(2000,2004,2008,2012)) +
  theme_publication() +
  theme(legend.position = "right", 
        legend.direction = "vertical",
        legend.title = element_text(face = "plain")) +
  guides(color = guide_colorbar(barheight = 10,
                                barwidth = 1.5,
                                ticks = FALSE,
                                nbin = 100)) +
#  guide_legend(title = 'Cohort') +
  facet_wrap(~riverFactor)#, scales = 'free_y') 
 


```







```{r early gams}
# some early exploration

# 1. Do we need separate splines on cohort in s()? YES, cohortOrdered is best
# 
mod0_0 <- bam(observedLength ~ cohort + s(ydayCumul, bs = 'cr'), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod0_1 <- bam(observedLength ~ cohort + s(ydayCumul, bs = 'cr', by = (cohort)), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod0_2 <- bam(observedLength ~ cohort + s(ydayCumul, bs = 'cr', by = (cohortFactor)), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod0_3 <- bam(observedLength ~ 
                cohort + 
                s(ydayCumul, bs = 'cr') + 
                s(ydayCumul, bs = 'cr', by = (cohortOrdered)), 
              data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod0_4 <- bam(observedLength ~ cohort + 
                s(ydayCumul, bs = 'cr') + 
                s(ydayCumul, bs = 'cr', by = (cohortOrderedSpecies)),
                data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

#mod0_4 is best
AIC(mod0_0,mod0_1,mod0_2,mod0_3,mod0_4) %>% rownames_to_column() %>% arrange(AIC)





# 2. structure of smooths
# with ordered factor, need to include an overall smooth, http://www.sfs.uni-tuebingen.de/~jvanrij/Tutorial/GAMM.html 
mod0_4a <- gam(observedLength ~ cohort + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = (cohortOrderedSpecies)), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod0_4b <- gam(observedLength ~ cohortOrdered + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = (cohortOrderedSpecies)), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

# mod0_3b is best, but we want to estimate a trend as in mod0_3a
# add + s(ydayCumul, bs = 'cr') to models
AIC(mod0_4,mod0_4a,mod0_4b) %>% rownames_to_column() %>% arrange(AIC)


# 3. gam vs. bam for this big dataset? bam() is MUCH faster!
system.time( mod0_4a_1 <- gam(observedLength ~ cohort + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = (cohortOrderedSpecies)), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML") )
# 316 sec
summary(mod0_3a_1)

system.time( mod0_4a_2 <- bam(observedLength ~ cohort + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = (cohortOrderedSpecies)), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML") )
# 8 sec
summary(mod0_4a_2)

# 4. bs = 'cr', vs default 'tp'. AIC for 'cr' is ~ 300 lower. Stick with 'cr'
mod0_4a_2a <- bam(observedLength ~ cohort + s(ydayCumul) + s(ydayCumul, by = (cohortOrderedSpecies)), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

AIC(mod0_4a_2,mod0_4a_2a)






# 5. Include Individual as a RE??
# Taking a long time, maybe run overnight
vB$tagIndexFactor <- factor(vB$tagIndex)
system.time( mod0_3a_3 <- bam(observedLength ~ year + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = (yearOrdered)) + s(ydayCumul, tagIndexFactor, bs="fs", m=1), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML") )
# sec
compareML(mod0_3a_3,mod0_3a_2)





# 2. Best structure for year,species,river
mod0 <- bam(observedLength ~ cohort + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod1 <- bam(observedLength ~ species + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod2 <- bam(observedLength ~ river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

# river expains the most for 1-variable models
AIC(mod0,mod1,mod2) %>% rownames_to_column() %>% arrange(AIC)

# 2-way models
mod3 <- bam(observedLength ~ cohort * species + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod4 <- bam(observedLength ~ cohort * river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

mod5 <- bam(observedLength ~ species * river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")

# mod4 is best
AIC(mod0,mod1,mod2,mod3,mod4,mod5) %>% rownames_to_column() %>% arrange(AIC)

# 3-way models
mod6 <- bam(observedLength ~ cohort * species * river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")
summary(mod6)

mod6a <- bam(observedLength ~ cohort * species * river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrderedSpecies), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")
summary(mod6a)

mod6b <- bam(observedLength ~ cohort * river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrderedSpecies), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")
summary(mod6b)

#mod6a is best
AIC(mod6,mod6a,mod6b) %>% rownames_to_column() %>% arrange(AIC)

# Any additive 3-way better? NO
mod7 <- bam(observedLength ~ cohort + species * river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')))

mod8 <- bam(observedLength ~ cohort * species + river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')))

mod9 <- bam(observedLength ~ cohort + species + river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr', by = cohortOrdered), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')))

AIC(mod1,mod2,mod3,mod4,mod5,mod6,mod7,mod8,mod9) %>% rownames_to_column() %>% arrange(AIC)

summary(mod6)
plot(mod6a)

hist(resid(mod6a))
gam.check(mod6a)

plot(mod6a, shade = TRUE, pages = 2,  seWithMean = TRUE)

#################################
# Predictions
# https://www.fromthebottomoftheheap.net/2017/10/10/difference-splines-i/

mod6a <- bam(observedLength ~ cohort * species * river + s(ydayCumul, bs = 'cr') + s(ydayCumul, bs = 'cr'), data = vB %>% filter(cohort %in% 2000:2013,species %in% c('bkt','bnt')), method = "REML")


predGrid <- expand.grid(cohortOrderedSpecies = unique(mod6a$model$cohortOrderedSpecies), 
                        river = mod6a$xlevels$river,  
                        ydayCumul = seq(250,1000, by = 30)) %>%
            mutate(cohort = as.numeric(substr(cohortOrderedSpecies,1,4)),
                   species = substr(cohortOrderedSpecies,6,8))

pred <- predict(mod6a, newdata = predGrid)#, type = 'lpmatrix')

predGrid2 <- bind_cols(predGrid,as.data.frame(pred))

ggplot(predGrid2, aes(ydayCumul,pred, color = species)) +
  geom_point() + 
  geom_line() +
  facet_grid(river ~ cohort)
```  



```{r models with season-do not run. gam structure given best model from above}

# BKT, mod0 is best fixed effects model

system.time(
mod0_YDCcr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod0_YDCc_r <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) , 
               data = dataIn, 
               method = "REML")
)

AIC(mod0_YDCcr, mod0_YDCc_r) %>% rownames_to_column() %>% arrange(AIC)


system.time(
mod0_YDCcr_Cr_CSr_Tr_Fr_TFr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = riverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = riverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = riverFactor), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod0_YDCcr_Cr_CSr_Ts_Fs_TFs <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = season) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = season) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = season), 
               data = dataIn, 
               method = "REML")
)
 
system.time(
mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)

AIC(mod0_YDCcr, mod0_YDCc_r, mod0_YDCcr_Cr_CSr_Tr_Fr_TFr, mod0_YDCcr_Cr_CSr_Ts_Fs_TFs,mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr) %>% rownames_to_column() %>% arrange(AIC)
summary(mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr) 
plot(mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr, pages = 8, shade = TRUE, scale = 0)

system.time(
mod0_YDCcr_C_CSr_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod0_YDCcr_Cr_CS_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod0_YDCcr_C_CS_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)

AIC(mod0_YDCcr, mod0_YDCc_r, mod0_YDCcr_Cr_CSr_Tr_Fr_TFr, mod0_YDCcr_Cr_CSr_Ts_Fs_TFs,mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr,mod0_YDCcr_C_CSr_Tsr_Fsr_TFsr,mod0_YDCcr_Cr_CS_Tsr_Fsr_TFsr,mod0_YDCcr_C_CS_Tsr_Fsr_TFsr) %>% rownames_to_column() %>% arrange(AIC)
summary(mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr) 
plot(mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr, pages = 8, shade = TRUE, scale = 0)


# take out s()'s

system.time(
mod0_YDCcr_Cr_CSr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod0_YDCcr_Cr_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               #s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)

system.time(
mod0_YDCcr_CSr_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
              # s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)


system.time(
mod0_YDCcr_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor * factor(season) + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
             #  s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
             #  s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)
########

AIC(mod0_YDCcr, mod0_YDCc_r, mod0_YDCcr_Cr_CSr_Tr_Fr_TFr, mod0_YDCcr_Cr_CSr_Ts_Fs_TFs,mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr,mod0_YDCcr_C_CSr_Tsr_Fsr_TFsr,mod0_YDCcr_Cr_CS_Tsr_Fsr_TFsr,mod0_YDCcr_Cr_CSr,mod0_YDCcr_C_CS_Tsr_Fsr_TFsr,mod0_YDCcr_Cr_Tsr_Fsr_TFsr,mod0_YDCcr_CSr_Tsr_Fsr_TFsr, mod0_YDCcr_Tsr_Fsr_TFsr, mod6_YDCcr_Cr_CSr_Tsr_Fsr_TFsr) %>% rownames_to_column() %>% arrange(AIC)

#                           rowname        df      AIC
# 1  mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr 277.67003 401304.4
# 2   mod0_YDCcr_C_CSr_Tsr_Fsr_TFsr 281.22421 401407.3
# 3   mod0_YDCcr_Cr_CS_Tsr_Fsr_TFsr 277.09498 401772.0
# 4     mod0_YDCcr_CSr_Tsr_Fsr_TFsr 279.84632 402037.9
# 5    mod0_YDCcr_C_CS_Tsr_Fsr_TFsr 269.69828 402073.1
# 6     mod0_YDCcr_Cr_CSr_Tr_Fr_TFr 207.97536 402187.1
# 7     mod0_YDCcr_Cr_CSr_Ts_Fs_TFs 190.64645 402464.7
# 8      mod0_YDCcr_Cr_Tsr_Fsr_TFsr 289.33427 403529.7
# 9         mod0_YDCcr_Tsr_Fsr_TFsr 283.93242 404139.1
# 10              mod0_YDCcr_Cr_CSr 184.24038 413605.9
# 11                     mod0_YDCcr 168.77693 420503.0
# 12                    mod0_YDCc_r  71.99108 422677.4

summary(mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr) 
plot(mod0_YDCcr_Cr_CSr_Tsr_Fsr_TFsr, pages = 8, shade = TRUE, scale = 0)

#AIC(mod6_YDCcr_Cr_CSr_Tsr_Fsr_TFsr)
#[1] 401367.4

#> AIC(mod6_YDCcr_Cr_CSr_Tr_Fr_TFr)
#[1] 402517.3

#########
# models with seasonal effects give a drop in seqson 1 sizes try models without seasonal effects
# may make sense because season is implicit in yDayCumul

# model without season in fixed
# this one gives a bump up in sizes for season 4
system.time(
mod6_YDCcr_Cr_CSr_Tsr_Fsr_TFsr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = seasonRiverFactor), 
               data = dataIn, 
               method = "REML")
)

# predictions from this models are smooth!
# use this as the base model
system.time(
mod6_YDCcr_Cr_CSr_Tr_Fr_TFr <- bam(observedLength ~ riverFactor + factor(salmon01) +              
               s(ydayCumul, bs = 'cr') +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = riverFactor) +
               s(ydayCumul, bs = 'cr', k = kIn, by = cohortRiverFactor) +
               s(cohort, bs = 'cr', k = kIn, by = riverFactor) + 
               s(cohortStrengthScaled, bs = 'cr', k = kIn, by = riverFactor) +  # this is conspecific cS only
               s(meanTemperatureScaledBySeason, bs = 'cr', k = kIn, by = riverFactor) +
               s(meanFlowScaledBySeason, bs = 'cr', k = kIn, by = riverFactor) +
               s(meanTemperatureFlowScaledBySeason, bs = 'cr', k = kIn, by = riverFactor), 
               data = dataIn, 
               method = "REML")
)

summary(mod6_YDCcr_Cr_CSr_Tr_Fr_TFr) 
plot(mod6_YDCcr_Cr_CSr_Tr_Fr_TFr, pages = 8, shade = TRUE, scale = 0)

```

```{r}
#earlier runs before setting fixed effect first. kept forf reference
# BKT 
#             rowname        df      AIC
# 1     modCR_SR_c_cS 162.34756 414267.2
# 2      modCR_S_c_cS 163.43154 414602.7
# 3        modCR_c_cS 161.63691 414750.3
# 4  modCR_SR_c_cSR3a  88.21646 415388.9
# 5  modCR_SR_c_cSR3b 167.32968 416062.3
# 6    modCR_SR_c_cSR 163.93920 416587.5
# 7   modCR_SR_c_cSR3 173.36884 416611.4
# 8         modCR_S_c 157.23995 418645.9
# 9           modCR_c 158.50186 418665.1
# 10            modCR 154.36186 419135.1
# 11           modC_R  63.10879 421258.1
# 12              mod  17.99204 427309.6
# 13             modC  48.73277 431440.2
# 14             modR  22.80483 432214.7

# BNT
#             rowname       df      AIC
# 1  modCR_SR_c_cSR3a 89.52290 231873.4
# 2  modCR_SR_c_cSR3b 89.54674 231873.6
# 3     modCR_SR_c_cS 84.40505 231935.7
# 4      modCR_S_c_cS 83.47382 231962.5
# 5   modCR_SR_c_cSR3 88.15840 232100.8
# 6        modCR_c_cS 80.92171 232142.0
# 7    modCR_SR_c_cSR 80.89406 232201.5
# 8         modCR_S_c 79.53048 232281.7
# 9           modCR_c 77.80808 232420.2
# 10            modCR 78.58400 233816.0
# 11           modC_R 53.21199 234214.3
# 12              mod 13.99759 238544.8
# 13             modR 14.97078 243472.0
# 14             modC 48.73277 431440.2

```

